spring:
  application:
    name: worthit-reminder

server:
  port: 18083

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
  enable-default-api-docs: false

---
spring:
  config:
    activate:
      on-profile: "local | dev | test"
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
  enable-default-api-docs: false
worthit:
  web:
    openapi:
      enabled: true
