<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.shaopc.worthit</groupId>
        <artifactId>worthit-server</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <artifactId>worthit-common</artifactId>
    <packaging>pom</packaging>
    <name>WorthIt Common</name>
    <modules>
        <module>worthit-common-core</module>
        <module>worthit-common-web</module>
        <module>worthit-common-webmvc-autoconfigure</module>
        <module>worthit-common-webmvc-starter</module>
        <module>worthit-common-security</module>
        <module>worthit-common-data</module>
        <module>worthit-common-http</module>
        <module>worthit-common-test</module>
    </modules>
</project>
